### PR TITLE
Add Korean MSX computers

### PR DESCRIPTION
**Pull request by juntaesu**
Daewoo MSX1
- DPC-100, DPC-180, DPC-200, DPC-200E(FR)

Daewoo MSX2
- CPC-400S : not working due to Toshiba FDC. It works when applying WD FDC bios.

Goldstar MSX1
- FC-80, FC-80U, FC-200, GFC-1080, GFC-1080A

Samsung MSX1
- SPC-800

Thanks,

### CODE REVIEW

**Comment by tdlabac** [comment]
Hi, please update the repository in the MSX2 branch and use the modified createMsxPack tool. In this version there is no need to align ROMs into 16kB blocks. This will be done automatically if needed. After that, use the original ROM for hanghul.

**Comment by juntaesu** [comment]
Understood. After testing, I'll update XML which include original rom.
Thanks,

**Comment by juntaesu** [comment]
I made changed 3 XMLs using 8kb original roms and confirmed its working.

**Comment by tdlabac** [comment]
Please next time in the extra branch that comes from the top of the branch where you want to merge it. Tahnks

**Comment by juntaesu** [comment]
Sorry for bothering. I forgot the sequence and next time I'll follow the right sequence.
Thanks

**Pull request merged**
